config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'pages/home'
  root to: 'pages#home'

  devise_for :users

  resources :users, only: [:show]
  resources :events
  resources :profiles, only: [:new, :edit, :create, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :events

  validates :name, presence: true, uniqueness: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories

  validates :name, presence: true
  validates :description, presence: true, length: {maximum: 500}
  validates :starts_at, presence: true
  validates :ends_at, presence: true
  validate :end_after_start

  private
  def end_after_start
    return if ends_at.blank? || starts_at.blank?

    if ends_at <= starts_at + 1.day
      errors.add(:ends_at, "must be after the start date")
    end
  end


end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events, dependent: :destroy

  has_one :profile

  def has_profile?
    profile.present? && !profile.id.nil?
  end

  def full_name
    profile.full_name
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
  end

  def show
    @categories = @event.categories
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to @event, notice: "Event successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: "Event successfully updated"
    else
      render :edit
    end
  end


  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :description, :location, :price, :capacity, :includes_food, :includes_drinks, :starts_at, :ends_at, :active, category_ids: [])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :bio)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <%= render 'shared/validation_errors' %>

   <div class="form-group">
     <label>Name</label>
     <%= f.text_field :name, placeholder: "Event name", class: "form-control" %>
   </div>

   <div class="form-group">
     <label>Description</label>
     <%= f.text_area :description, rows: 5, placeholder: "Say something about your place", class: "form-control" %>
   </div>

   <div class="form-group">
     <label>Location</label>
     <%= f.text_field :location, placeholder: "Location", class: "form-control" %>
   </div>

   <div class="form-group">
     <label>Price</label>
     <div class="input-group">
       <div class="input-group-addon">€</div>
       <%= f.number_field :price, placeholder: "eg. 100", class: "form-control" %>
     </div>
   </div>

   <div class="form-group">
     <label>Number of Guests</label>
     <%= f.select :capacity, [["10", 10], ["20", 20], ["30", 30], ["40", 40], ["50", 50], ["60", 60], ["70", 70], ["80", 80], ["90", 90], ["100", 100]], prompt: "Select number of guests", class: "form-control" %>
   </div>

   <div class="form-group">
     <label>Starts at</label>
     <%= f.datetime_select :starts_at, start_year: Date.current.year, use_month_numbers: false, minute_step: 15 %>
   </div>

   <div class="form-group">
     <label>Ends at</label>
     <%= f.datetime_select :ends_at, start_year: Date.current.year, use_month_numbers: false, minute_step: 15 %>
   </div>

   <hr>

   <label>Amenities</label>

   <div class="form-group">
     <%= f.check_box :includes_food %> Food
   </div>
   <div class="form-group">
     <%= f.check_box :includes_drinks %> Drinks
   </div>

   <hr>

   <label>Categories</label>

   <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
     <div class="form-group">
       <%= b.check_box(class: "check_box") %> <%= b.object.name %>
     </div>
   <% end %>

   <hr>


   <label>Publish this event?</label>

   <div class="form-group">
     <%= f.check_box :active %> Active
   </div>

   <div class="actions">
     <%= f.submit "Save", class: "btn btn-success" %>
   </div>
 <% end %>

app/views/events/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", events_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", events_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your Listings
      </div>
      <div class="panel-body">

        <% @events.each do |event| %>
        <div class="row">
          <div class="col-md-7">
            <h4><%= event.name %></h4>
          </div>
          <div class="col-md-3 right">
            <%= link_to "View", event, class: "btn btn-default" %>
            <%= link_to "Update", edit_event_path(event), class: "btn btn-default" %>
          </div>
        </div>
        <% end %>

      </div>
    </div>

    <%= link_to "Add new event", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><%= @event.name %></div>

  <div class="panel-body">

    <p>Location: <%= @event.location %></p>
    <p>Host: <%= @event.user.email %></p>

    <!-- Main Info -->
    <h4>Main Info</h4>
    <p>Description: <%= @event.description %></p>

    <p> From: <%= @event.starts_at %></p>
    <p> Until: <%= @event.ends_at %></p>
    <p> Capacity: <%= @event.capacity %></p>

    <!-- About -->
    <h4>Price</h4>
    <p><%= @event.price %></p>

    <!-- Amenities -->
    <h4>Amenities</h4>
    <ul class="amenities">
      <li><%= !@event.includes_food ? ("<s>Food</s>").html_safe : "Food included" %></li>
      <li><%= !@event.includes_drinks ? ("<del>Drinks</del>").html_safe : "Drinks included" %></li>
    </ul>

    <h4>Categories</h4>
    <% @categories.each do |category| %>
      <span class="label label-success"><%= category.name %></span>
    <% end %>


  </div>

</div>

<%= link_to "Back", events_path, class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HubUp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <% @profile.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Bio</label>
    <%= f.text_area :bio, rows: 5, placeholder: "Say something about yourself", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Back", root_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/profiles/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Create your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"><%= link_to "HubUp", root_path, class: "navbar-brand"  %></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-left" float="left"><img src="http://oi66.tinypic.com/kby72q.jpg"></div>
      <%= link_to "HubUp", root_path, class: "navbar-brand"  %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_user.has_profile? ? current_user.full_name : current_user.email  %> <span class="caret"></span>
              <ul class="dropdown-menu">
                <li><%= link_to "Your Events", events_path %></li>
                <li role="separator" class="divider"></li>

                <% if current_user.has_profile? %>
                <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
                <% else %>
                <li><%= link_to "Create Profile", new_profile_path %></li>
                <% end %>
                <li><%= link_to "Edit Password", edit_user_registration_path %></li>

                <li role="separator" class="divider"></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
    </ul>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/shared/_validation_errors.html.erb
<% if @event.errors.any? %>
  <% @event.errors.full_messages.each do |message| %>
    <span class="label label-danger"><%= message %></span>
  <% end %>
<% end %>